---
name: CICD
on:
  workflow_dispatch: null

jobs:
  # every job needs a separate runner, it's called parallelism
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "Code Clone from GitHub"

  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Container
        run: echo "Docker Container build"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test the container
        run: echo "Testing the container"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the app
        run: echo "Docker compose deployed the app"
